### ISSUE TITLE
关于chat_template

### ISSUE THREAD

**Issue by leekaimao** [Tele-AI/TeleChat2#11]
最近在看teleai的源码中有默认的chat_template,但其中没有关于system字段的设置。我想在我的微调数据中加上我的任务描述，想添加在system字段中。是这个模型本身的tokenize过程不支持system字段的chat_template，还是说是可以设置的。

**Comment by shunxing12345** [comment]
您好，我们11月份开源的模型都已经适配了system字段关于具体的chat template可以参考
https://modelscope.cn/models/TeleAI/TeleChat2-35B-Nov/file/view/master?fileName=tokenizer_config.json&status=1#L113
这里。
微调可以参考我们deepspeed的里的文档。

**Comment by leekaimao** [comment]
之前开放的12b的telechat模型也是适配system字段的吗？deepspeed文档里的方法对于昇腾也是一样适用的吗？此外，想请教一下：TeleAI是因果解码器架构吗，输入输出没有明显分界，所以微调时将一个对话的的多轮内容一次性输入模型。通过设计损失掩码来实现针对每轮对话的模型输出部分进行损失计算，从而显著减少重复前缀计算的开销。还是说只是decoder-only架构？

**Comment by leekaimao** [comment]
> 您好，我们11月份开源的模型都已经适配了system字段关于具体的chat template可以参考 https://modelscope.cn/models/TeleAI/TeleChat2-35B-Nov/file/view/master?fileName=tokenizer_config.json&status=1#L113 这里。 微调可以参考我们deepspeed的里的文档。

**Comment by shunxing12345** [comment]
您好，之前开源的12不适配现在的system字段，我们最近在modelscope开源的新12b适配system字段欢迎尝试。对于deepspeed里的方法现只使用与deepspeed，昇腾适配文档我们正在完善。telechat 是decoder only 架构
