### ISSUE TITLE
910b推理

### ISSUE THREAD

**Issue by cccusername** [Tele-AI/TeleChat2#13]
按照指引进行，利用910推理，会报错flashattention
![微信截图_20241118110938](https://github.com/user-attachments/assets/a5d0b3dd-283b-4eb8-b40c-faba65d0f153)

把flashattention取消后又y有其他报错
![微信截图_20241118112110](https://github.com/user-attachments/assets/f597ac5c-f31c-4c23-b65f-da06f42ef2d9)

能否提供更详细的教程，或者告知一下环境的版本要求，如mindspore等

**Comment by liuxz0801** [comment]
您好，您的这个报错是mindformers分支不稳定引起的。本周我们会fork给出稳定分支和配套教程。

**Comment by liuxz0801** [comment]
https://github.com/Tele-AI/TeleChat2/blob/main/tutorial/telechat_%E5%9B%BD%E4%BA%A7%E5%8C%96%E8%BF%90%E8%A1%8C.md
欢迎您按照教程运行telechat。
