### ISSUE TITLE
pip install -r requirements 报错

### ISSUE THREAD

**Issue by yechaoying** [Tele-AI/TeleChat2#24]
报错信息：
Collecting accelerate>=0.34.2 (from -r requirements.txt (line 1))
  Downloading accelerate-1.1.1-py3-none-any.whl.metadata (19 kB)
Collecting deepspeed==0.15.1 (from -r requirements.txt (line 2))
  Downloading deepspeed-0.15.1.tar.gz (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting datasets>=3.0.0 (from -r requirements.txt (line 3))
  Downloading datasets-3.1.0-py3-none-any.whl.metadata (20 kB)
Collecting flash-attn (from -r requirements.txt (line 4))
  Downloading flash_attn-2.7.0.post2.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 27.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l6uygyyp/flash-attn_f2a6f3fd9dd24d8d9ef264e48b7f15b5/setup.py", line 21, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
----------------------------------------------------------------------------------
 flash-attn 的安装看起来依赖于 torch，但是requirements.txt里也有torch==2.4.0，是否可以提供一个可以流畅安装的requirements.txt

**Comment by nsygh1** [comment]
requirments.txt漏东西了。而且结果我的实践发现，先装torch，再装flash-attn同样报错。另外，deepspeed没办法利用pip安装，可能需要手动安装。能问一下过了这么长时间，你的环境配好了吗

**Comment by yechaoying** [comment]
你好，我还没有安装好，先搁置了，另一个telechat室友docker文件的，那个用docker可以运行，还没有来得及看Telechat2可不可以用那个的docker环境运行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月7日(周六) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tele-AI/TeleChat2] pip install -r requirements 报错 (Issue #24)




 
requirments.txt漏东西了。而且结果我的实践发现，先装torch，再装flash-attn同样报错。另外，deepspeed没办法利用pip安装，可能需要手动安装。能问一下过了这么长时间，你的环境配好了吗

**Comment by yechaoying** [comment]
你好，成功运行telechat_infer_demo.py的环境配置如下，参考了deepspeed的环境设置以及main中的requirement.txt
我这里是CUDA Version: 12.4，应该大于 cuda tookit的版本就行

```
conda create -n tele python=3.10
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
pip install transformers==4.45.0 
```

直接“pip install deepspeed==0.9.3”会报错”AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)“
先安装CUDA Toolkit:`nvcc` 是 CUDA Toolkit 中的编译器，如果安装了 CUDA Toolkit，应该可以通过命令行`nvcc --version`调用 `nvcc`。

同时后面FlashAttention的包flash-attn要求 CUDA 版本为 **11.7** 或更高版本![image-20241211104119105](https://ycy-lenovo-typora.oss-cn-beijing.aliyuncs.com/typora_imgs/image-20241211104119105.png)

不要`sudo apt install nvidia-cuda-toolkit`安装cuda toolkit，这里的默认版本是11.5的，由于没看到仓库具体用的是哪个版本的cuda toolkit,这里用了11.8

```
wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
sudo sh cuda_11.8.0_520.61.05_linux.run
```

然后

```
pip install deepspeed==0.9.3
pip install flash-attn==2.0.0.post1
pip install sentencepiece
pip install accelerate>=0.34.2
```

如果出现报错:A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

```
pip install "numpy<2"
```

如果出现NameError:name'Extension' is not defined,Did you mean:'Exception'?

检查一下是否安装了jinja2这个包，如果没安装，`jinja2.ext` 模块中的 `Extension` 类没有正确导入，就会报这个错

```
pip install jinja2
```

然后这样就可以运行telechat_infer_demo.py

**Comment by nsygh1** [comment]
非常感谢你的解决方案，但是我安装这个项目的系统为Windows11系统，我在Windows11上安装这个项目碰到的报错和你给的方案里面的报错是不一样的，而且我也是穷学生，没有钱去租一个Linux服务器，能否冒昧地请求一下您做一下Window11系统上的安装方案？如果您愿意，我将不胜感激。
